import { Printer } from "lucide-react"

import { PageHeader } from "@/components/common/PageHeader"
import {
  Card,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { useAnalytics } from "@/hooks/use-analytics"
import { formatCurrency, formatNumber } from "@/lib/formatters"

export function ReportsPage() {
  const { hasData, kpis, insights, spendByVendor } = useAnalytics()

  const handlePrint = () => {
    window.print()
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 print:hidden">
        <PageHeader
          title="Reports"
          description="Generate shareable procurement reports from your analyzed data."
        />
        {hasData && (
          <Button onClick={handlePrint} className="shrink-0 gap-2">
            <Printer className="size-4" />
            Print / Save as PDF
          </Button>
        )}
      </div>

      {!hasData ? (
        <Card className="print:hidden">
          <CardHeader>
            <CardTitle>No data available</CardTitle>
            <CardDescription>Upload a workbook to unlock reporting capabilities.</CardDescription>
          </CardHeader>
        </Card>
      ) : (
        <div className="space-y-8 print:block">
          
          {/* Printable Report Header */}
          <div className="hidden print:block space-y-2 mb-8">
            <h1 className="text-3xl font-bold tracking-tight">Procurement Summary Report</h1>
            <p className="text-muted-foreground">Generated via CostCompass</p>
          </div>

          {/* Financial Highlights */}
          <div className="grid grid-cols-3 gap-4 border-y py-4 my-6">
            <div>
              <p className="text-xs text-muted-foreground">TOTAL SPEND</p>
              <p className="text-xl font-bold">{kpis ? formatCurrency(kpis.totalSpend) : "—"}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">ACTIVE VENDORS</p>
              <p className="text-xl font-bold">{kpis ? formatNumber(kpis.uniqueVendors) : "—"}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">TOTAL MATERIALS</p>
              <p className="text-xl font-bold">{kpis ? formatNumber(kpis.uniqueMaterials) : "—"}</p>
            </div>
          </div>

          {/* Key Findings / AI Insights */}
          <div className="space-y-4">
            <h3 className="font-semibold text-base text-foreground">Strategic Observations</h3>
            {insights.length === 0 ? (
              <p className="text-sm text-muted-foreground italic">No anomalies or significant spend patterns detected.</p>
            ) : (
              <div className="space-y-3">
                {insights.map((insight, idx) => (
                  <div key={idx} className="border-l-2 border-primary pl-3 py-1">
                    <p className="text-sm font-medium">{insight.title}</p>
                    <p className="text-xs text-muted-foreground">{insight.description}</p>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Top Vendors Table */}
          <div className="mt-8 space-y-2">
            <h3 className="font-semibold text-base text-foreground">Top 5 Vendors by Volume</h3>
            <table className="w-full text-left text-sm border-collapse">
              <thead>
                <tr className="border-b text-xs text-muted-foreground">
                  <th className="py-2">Vendor</th>
                  <th className="py-2 text-right">Spend</th>
                </tr>
              </thead>
              <tbody>
                {spendByVendor.slice(0, 5).map((v) => (
                  <tr key={v.vendor} className="border-b last:border-0">
                    <td className="py-2">{v.vendor}</td>
                    <td className="py-2 text-right font-medium">{formatCurrency(v.spend)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Report Footer */}
          <div className="mt-12 text-center text-xs text-muted-foreground border-t pt-4">
            Confidential - Generated by CostCompass
          </div>
        </div>
      )}
    </div>
  )
}
