import { Printer, FileText } from "lucide-react"

import { PageHeader } from "@/components/common/PageHeader"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { useAnalytics } from "@/hooks/use-analytics"
import { formatCurrency, formatNumber } from "@/lib/formatters"

export function ReportsPage() {
  const { hasData, kpis } = useAnalytics()

  const handlePrint = () => {
    window.print()
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 print:hidden">
        <PageHeader
          title="Reports"
          description="Generate shareable procurement reports from your analyzed data."
        />
        {hasData && (
          <Button onClick={handlePrint} className="shrink-0 gap-2">
            <Printer className="size-4" />
            Print / Save as PDF
          </Button>
        )}
      </div>

      {!hasData ? (
        <Card className="print:hidden">
          <CardHeader>
            <CardTitle>No data available</CardTitle>
            <CardDescription>Upload a workbook to unlock reporting capabilities.</CardDescription>
          </CardHeader>
        </Card>
      ) : (
        <div className="space-y-8 print:block">
          
          {/* Printable Report Header */}
          <div className="hidden print:block space-y-2 mb-8">
            <h1 className="text-3xl font-bold tracking-tight">Procurement Summary Report</h1>
            <p className="text-muted-foreground">Generated via ProcureLens</p>
            <hr className="my-4" />
          </div>

          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
            <Card>
              <CardHeader className="pb-2">
                <CardDescription>Total Spend</CardDescription>
                <CardTitle className="text-3xl">{kpis ? formatCurrency(kpis.totalSpend) : "-"}</CardTitle>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader className="pb-2">
                <CardDescription>Vendors</CardDescription>
                <CardTitle className="text-3xl">{kpis ? formatNumber(kpis.uniqueVendors) : "-"}</CardTitle>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader className="pb-2">
                <CardDescription>Materials</CardDescription>
                <CardTitle className="text-3xl">{kpis ? formatNumber(kpis.uniqueMaterials) : "-"}</CardTitle>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader className="pb-2">
                <CardDescription>Avg Order Value</CardDescription>
                <CardTitle className="text-3xl">{kpis ? formatCurrency(kpis.averageOrderValue) : "-"}</CardTitle>
              </CardHeader>
            </Card>
          </div>

          <Card className="print:break-inside-avoid">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="size-5" />
                Executive Summary
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="leading-relaxed text-muted-foreground">
                This report summarizes {kpis?.uniqueMaterials} unique materials procured from {kpis?.uniqueVendors} active vendors. 
                The total expenditure for this period amounts to {kpis ? formatCurrency(kpis.totalSpend) : ""}, 
                with an average order value of {kpis ? formatCurrency(kpis.averageOrderValue) : ""}. 
                Please refer to the Insights tab for detailed anomaly detection and cost-saving recommendations.
              </p>
            </CardContent>
          </Card>
          
          <div className="hidden print:block text-sm text-center text-muted-foreground pt-12">
            Confidential - Generated by ProcureLens
          </div>
        </div>
      )}
    </div>
  )
}
